version: '3.8'

services:
  app:
    container_name: my-golang-app
    build: .
    ports:
      - "8084:80" 
    networks:
      - net_my_compose_joycepatrcia
    depends_on:
      - database  
    environment:
      - DB_HOST=localhost
      - DB_PORT=5435
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"  # Exposing PostgreSQL on port 5435 on the host
    networks:
      - net_my_compose_joycepatrcia
    volumes:
      - vol_my_compose_joycepatrcia:/var/lib/postgresql/data  

networks:
  net_my_compose_joycepatrcia:
    driver: bridge

volumes:
  vol_my_compose_joycepatrcia: 
